config/routes.rb
Rails.application.routes.draw do
  root to: 'orders#index'

  resources :orders, only: %i[index create show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  validates_presence_of :description
  validates_presence_of :price
end

app/models/merchant.rb
class Merchant < ApplicationRecord
  validates_presence_of :name
  validates_presence_of :address
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :purchases

  def value
    purchases.includes(:item).sum('price * quantity')
  end
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  validates_presence_of :quantity
  
  belongs_to :order
  belongs_to :item
  belongs_to :merchant
  belongs_to :purchaser
end

app/models/purchaser.rb
class Purchaser < ApplicationRecord
  validates_presence_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  
  def index
    @orders = Order.all.order(id: :desc)
  end

  def show
    @order = Order.includes(:purchases).find(params[:id])
  end

  def create
    order_file = params[:file]
    result = ParseOrderFile.call(file: order_file, locale: :pt)
    @order = result.order 
    respond_to do |format|
      format.js
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevNuuvemTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/_dropzone.html.erb
<div class="upload-wrapper">
    <%= form_with url: orders_path(format: :js), remote: true, local: false, class: "dropzone", id: "my-awesome-dropzone" do |form| %>
    <% end %>
</div>

<script>
    
    Dropzone.options.myAwesomeDropzone = {
        paramName: "file", // The name that will be used to transfer the file
        dictDefaultMessage: "Click or drag to upload files",
        dictFileTooBig: "Very large file. Limit: 20mb",
        maxFilesize: 20, // MB
        success: response => eval(response.xhr.response)
    };
</script>

app/views/orders/_order.html.erb
<tr>
    <td>Pedido <%= order.id %></td>
    <td> <%= order.created_at.strftime('%m/%d/%Y') %></td>
    <td><%= number_to_currency(order.value, :unit => "R$ ", :separator => ",", :delimiter => ".") %></td>
    <td><%= link_to "Details", order_path(order) %></td>
</tr>

app/views/orders/create.js.erb
$("#orders-wrapper tbody").prepend("<%= j render @order %>");

app/views/orders/index.html.erb
<div class="container">
  <div style="margin: 15px">
    <h1>Gerenciar pedidos</h2>
  </div>
  <%= render "dropzone" %>
  <div id="orders-wrapper" >
    <table class="table">
        <thead>
            <tr>
                <th>Order</th>
                <th>Date</th>
                <th>Total</th>
                <th>Details</th>
            <tr>
        <thead>
        <tbody>
          <%= render @orders %>
          <% if @orders.empty? %>
            <tr>
              <td>Nenhum arquivo enviado.</td>
            </tr>
          <% end %>
        </tbody>
      </thead>
    </table>

  <div>
</div>

app/views/orders/show.html.erb
<div class="container">
    <h1>Pedido <%= @order.id %></h1>
    <div>
        <table class="table shadow">
            <thead>
                <tr>
                    <th>Purchaser</th>
                    <th>Item Description</th>
                    <th>Item Price</th>
                    <th>Quantity</th>
                    <th>Merchant Address</th>
                    <th>Merchant Name</th>
                <tr>
            <thead>
            <tbody>
                <% @order.purchases.each do |purchase| %>
                    <tr>
                        <td><%= purchase.purchaser.name %></td>
                        <td><%= purchase.item.description %></td>
                        <td><%= number_to_currency(purchase.item.price, :unit => "R$ ", :separator => ",", :delimiter => ".") %></td>
                        <td><%= purchase.quantity %></td>
                        <td><%= purchase.merchant.address %></td>
                        <td><%= purchase.merchant.name %></td>
                    </tr>
                <% end %>
                <tr>
                <td></td>
                <td align="right" ><strong>Total: </strong></td>
                <td><%= number_to_currency(@order.value, :unit => "R$ ", :separator => ",", :delimiter => ".") %></td>
                <td></td>
                <td></td>
                <td></td>
                <tr>
            </tbody>
        </table>
        <%= link_to "Voltar", orders_path, class: "btn btn-info" %>
    <div>
</div>